### ISSUE TITLE
Update the linux version of MS-DIAL?

### ISSUE THREAD

**Issue by liaochenlanruo** [systemsomicslab/MsdialWorkbench#178]
Dear developers,
Do you have the plan to update the Linux version, as you know there are a lot of Linux users.
Thanks!

**Comment by kozo2** [comment]
Yes we have the plan. 
To update the Linux version, we need to first update the Windows version
(, and we are now managing it at https://github.com/systemsomicslab/MsdialWorkbench/issues/131).
By the way, we do not plan to provide only a command line tool for the Linux version.

This is because the command line tool and what it requires is implemented in .net standard or core, so we can build the Linux version (command line tool), but we cannot do that for the entire desktop GUI.
