### ISSUE TITLE
Exporting spectra in MassBank format

### ISSUE THREAD

**Issue by JeanFromentNILU** [systemsomicslab/MsdialWorkbench#331]
Hello,

I was wondering if I could ask some questions about the possibility to export spectra from MS-DIAL in MassBank format. In the new versions (5.3.240311 and others versions 5+) it is not possible to only export one spectra in MassBank format: unless I am mistaken, the export option is only available in the Peak spot and Alignment export tabs. Is that correct? Any idea on how to export only one selected spectra in MassBank format?

In my lab we also noticed that the MassBank export option is only available in LC projects and not GC. Would it be possible to have this option for GC projects in the future versions?

Cheers
Jean

**Comment by YukiMatsuzawa** [comment]
Hello, and thank you for using our software.

Yes, as you mentioned, it is currently not possible to export a single spectrum in the MassBank format. In the Alignment Export tab, it is possible to apply current filtering to export, potentially leaving only a single peak (though admittedly, this method is quite cumbersome). The easiest method to export a specific spectrum right now might be through using tags or comments along with the filtering feature.

Regarding the implementation of this option for GCMS projects in the future, it is indeed planned, along with enhancing the functionality to export single peak spots. However, due to our current development load, these features might not be implemented immediately. We apologize for any inconvenience this may cause.

Yuki

<img width="713" alt="image" src="https://github.com/systemsomicslab/MsdialWorkbench/assets/122433968/8b40c86f-5517-41cf-8fbd-90a9ef28aed7">
